---
swagger: "2.0"
info:
  description: "API-prototype"
  version: "1.0"
  title: "API-prototype"
schemes:
- "https"
paths:
  /auth:
    post:
      tags:
      - "users"
      summary: "Get access token for the user"
      operationId: "get_token"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "userCredentials"
        required: true
        schema:
          $ref: "#/definitions/UserCredentials"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Token"
        400:
          description: "No user with such email"
          schema:
            $ref: "#/definitions/Error"
        403:
          description: "Invalid email/password"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
        501:
          description: "Wrong request"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.users_controller"
  /users:
    get:
      tags:
      - "users"
      summary: "List all users"
      operationId: "list_users"
      produces:
      - "application/json"
      parameters:
      - name: "page"
        in: "query"
        description: "Page number of results to return. Starting from 1. Default 1."
        required: false
        type: "string"
      - name: "per_page"
        in: "query"
        description: "Number of items on page. Default 30."
        required: false
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Users"
        401:
          description: "No user token"
          schema:
            $ref: "#/definitions/Error"
        403:
          description: "Operation is not permitted for the user"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
        501:
          description: "Wrong request"
          schema:
            $ref: "#/definitions/Error"
      security:
      - Bearer: []
      x-swagger-router-controller: "swagger_server.controllers.users_controller"
    post:
      tags:
      - "users"
      summary: "Create a user"
      operationId: "create_user"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "newUser"
        required: true
        schema:
          $ref: "#/definitions/NewUser"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/NewUserResponse"
        401:
          description: "No user token"
          schema:
            $ref: "#/definitions/Error"
        403:
          description: "Operation is not permitted for the user"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
        501:
          description: "Wrong request"
          schema:
            $ref: "#/definitions/Error"
      security:
      - Bearer: []
      x-swagger-router-controller: "swagger_server.controllers.users_controller"
    put:
      tags:
      - "users"
      summary: "Update details of particular user"
      operationId: "update_user"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "newUser"
        required: true
        schema:
          $ref: "#/definitions/UpdateUser"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Empty"
        401:
          description: "No user token"
          schema:
            $ref: "#/definitions/Error"
        403:
          description: "Operation is not permitted for the user"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
        501:
          description: "Wrong request"
          schema:
            $ref: "#/definitions/Error"
      security:
      - Bearer: []
      x-swagger-router-controller: "swagger_server.controllers.users_controller"
  /users/{userId}:
    get:
      tags:
      - "users"
      summary: "Info for a specific user"
      operationId: "get_user"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        description: "The id of the user to retrieve"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/User"
        401:
          description: "No user token"
          schema:
            $ref: "#/definitions/Error"
        403:
          description: "Operation is not permitted for the user"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
        501:
          description: "Wrong request"
          schema:
            $ref: "#/definitions/Error"
      security:
      - Bearer: []
      x-swagger-router-controller: "swagger_server.controllers.users_controller"
    delete:
      tags:
      - "users"
      summary: "Delete the user"
      operationId: "delete_user"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        description: "The id of the user to delete"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Empty"
        401:
          description: "No user token"
          schema:
            $ref: "#/definitions/Error"
        403:
          description: "Operation is not permitted for the user"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
        501:
          description: "Wrong request"
          schema:
            $ref: "#/definitions/Error"
      security:
      - Bearer: []
      x-swagger-router-controller: "swagger_server.controllers.users_controller"
  /projects:
    get:
      tags:
      - "projects"
      summary: "List of all projects for user (own & shared))"
      operationId: "list_projects"
      produces:
      - "application/json"
      parameters:
      - name: "page"
        in: "query"
        description: "Page number of results to return. Starting from 1. Default 1."
        required: false
        type: "string"
      - name: "per_page"
        in: "query"
        description: "Number of items on page. Default 30."
        required: false
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Projects"
        401:
          description: "No user token"
          schema:
            $ref: "#/definitions/Error"
        403:
          description: "Operation is not permitted for the user"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
        501:
          description: "Wrong request"
          schema:
            $ref: "#/definitions/Error"
      security:
      - Bearer: []
      x-swagger-router-controller: "swagger_server.controllers.projects_controller"
    post:
      tags:
      - "projects"
      summary: "Create a project"
      operationId: "create_project"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "newProject"
        required: true
        schema:
          $ref: "#/definitions/NewProject"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/NewProjectResponse"
        401:
          description: "No user token"
          schema:
            $ref: "#/definitions/Error"
        403:
          description: "Operation is not permitted for the user"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
        501:
          description: "Wrong request"
          schema:
            $ref: "#/definitions/Error"
      security:
      - Bearer: []
      x-swagger-router-controller: "swagger_server.controllers.projects_controller"
  /projects/{projectId}:
    get:
      tags:
      - "projects"
      summary: "Info for a specific project"
      operationId: "get_project"
      produces:
      - "application/json"
      parameters:
      - name: "projectId"
        in: "path"
        description: "The id of the project to retrieve"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Project"
        401:
          description: "No user token"
          schema:
            $ref: "#/definitions/Error"
        403:
          description: "Operation is not permitted for the user"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
        501:
          description: "Wrong request"
          schema:
            $ref: "#/definitions/Error"
      security:
      - Bearer: []
      x-swagger-router-controller: "swagger_server.controllers.projects_controller"
    delete:
      tags:
      - "projects"
      summary: "Delete project"
      operationId: "delete_project"
      produces:
      - "application/json"
      parameters:
      - name: "projectId"
        in: "path"
        description: "The id of the project to delete"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Empty"
        401:
          description: "No user token"
          schema:
            $ref: "#/definitions/Error"
        403:
          description: "Operation is not permitted for the user"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
        501:
          description: "Wrong request"
          schema:
            $ref: "#/definitions/Error"
      security:
      - Bearer: []
      x-swagger-router-controller: "swagger_server.controllers.projects_controller"
securityDefinitions:
  Bearer:
    description: "JWT from /auth request"
    type: "apiKey"
    name: "Authorization"
    in: "header"
definitions:
  UserCredentials:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"
    example:
      password: "password"
      email: "email"
  Token:
    type: "object"
    properties:
      token:
        type: "string"
        description: "User jwt token"
    example:
      token: "token"
  Users:
    type: "array"
    items:
      $ref: "#/definitions/UserShort"
  UserShort:
    type: "object"
    properties:
      group:
        $ref: "#/definitions/UserGroup"
      email:
        type: "string"
      name:
        type: "string"
  UpdateUser:
    type: "object"
    properties:
      group:
        $ref: "#/definitions/UserGroup"
      email:
        type: "string"
      name:
        type: "string"
    example:
      name: "name"
      email: "email"
      group: {}
  NewUser:
    $ref: "#/definitions/UpdateUser"
  User:
    allOf:
    - $ref: "#/definitions/UpdateUser"
    - type: "object"
      properties:
        id:
          type: "string"
  UserGroup:
    type: "string"
    enum:
    - "admin"
    - "full"
    - "guest"
  Projects:
    type: "array"
    items:
      $ref: "#/definitions/ProjectShort"
  ProjectShort:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
  NewProject:
    type: "object"
    required:
    - "name"
    properties:
      name:
        type: "string"
    example:
      name: "name"
  Project:
    allOf:
    - $ref: "#/definitions/NewProject"
    - type: "object"
      properties:
        id:
          type: "string"
  NewUserResponse:
    type: "object"
    required:
    - "id"
    properties:
      id:
        type: "string"
        description: "ID of the created user"
    example:
      id: "id"
  NewProjectResponse:
    type: "object"
    required:
    - "id"
    properties:
      id:
        type: "string"
        description: "ID of the created project"
    example:
      id: "id"
  UserToShareWith:
    type: "object"
    properties:
      email:
        type: "string"
        description: "email of user to share with"
  Empty:
    type: "object"
  Error:
    type: "object"
    properties:
      status:
        type: "string"
        description: "error message"
responses:
  401:
    description: "No user token"
    schema:
      $ref: "#/definitions/Error"
  403:
    description: "Operation is not permitted for the user"
    schema:
      $ref: "#/definitions/Error"
  500:
    description: "Internal server error"
    schema:
      $ref: "#/definitions/Error"
  501:
    description: "Wrong request"
    schema:
      $ref: "#/definitions/Error"
