exclude: |
    (?x)(
        tests/|
        stress/|
        setup.py|
        src/alembic/|
        openapi_server/models/|
        openapi_server/controllers/|
        openapi_server/util.py|
        openapi_server/__main__.py|
        openapi_server/typing_utils.py|
        openapi_server/apikey_fake.py
    )
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.3
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: MyPy
        entry: |
          mypy
          --ignore-missing-imports
          --install-types
          --non-interactive
          --strict
          --implicit-reexport
          --warn-unused-ignores
          --cache-fine-grained
          --no-namespace-packages
#        require_serial: true
        files: \.py$
        language: python

      - id: pylint
        name: Pylint
        entry: |
          bash -c 'PYTHONPATH=. pylint \
          --max-line-length=99 \
          --ignore-imports=yes \
          --extension-pkg-allow-list=openapi_server.controllers \
          "$@"' --
        files: \.py$
        language: python

