  sudo: required
  language: python
  python:
    - "3.6"
    - "3.7-dev"
  install:
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
    - pip install python-coveralls codecov
  script:
    - pytest -s
  after_success:
    - coveralls
    - codecov
