  sudo: required
  language: python
  python:
    - "3.6"
    - "3.7-dev"
  install:
    - pip install -r requirements.txt
    - pip install -r requirements_test.txt
    - pip install --upgrade pytest
  script:
    - pytest -s -v --doctest-modules --cov src --cov-report term-missing --ignore src/alembic --ignore swagger-codegen --ignore src/flask_server/api_app.py -W ignore::DeprecationWarning
  after_success:
    - coveralls
