version: '3'
services:
  back:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  nginx:
    build:
      context: nginx
    ports:
      - "443:443"
    depends_on:
      - back
  db:
#    restart: always
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=testdb


