# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List, Optional  # noqa: F401

from openapi_server import util
from openapi_server.models.base_model_ import Model


class NewProjectResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: Optional[str] = None):  # noqa: E501
        """NewProjectResponse - a model defined in Swagger

        :param id: The id of this NewProjectResponse.  # noqa: E501
        :type id: str
        """
        self.swagger_types = {"id": str}

        self.attribute_map = {"id": "id"}

        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> "NewProjectResponse":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NewProjectResponse of this NewProjectResponse.  # noqa: E501
        :rtype: NewProjectResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this NewProjectResponse.

        ID of the created project  # noqa: E501

        :return: The id of this NewProjectResponse.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this NewProjectResponse.

        ID of the created project  # noqa: E501

        :param id: The id of this NewProjectResponse.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id
