# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List, Optional  # noqa: F401

from openapi_server import util
from openapi_server.models.base_model_ import Model


class NewProject(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: Optional[str] = None):  # noqa: E501
        """NewProject - a model defined in Swagger

        :param name: The name of this NewProject.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {"name": str}

        self.attribute_map = {"name": "name"}

        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> "NewProject":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NewProject of this NewProject.  # noqa: E501
        :rtype: NewProject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this NewProject.


        :return: The name of this NewProject.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this NewProject.


        :param name: The name of this NewProject.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name
