from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.user_group import UserGroup
from openapi_server import util

from openapi_server.models.user_group import UserGroup  # noqa: E501

class UserShort(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, group=None, email=None, name=None):  # noqa: E501
        """UserShort - a model defined in OpenAPI

        :param group: The group of this UserShort.  # noqa: E501
        :type group: UserGroup
        :param email: The email of this UserShort.  # noqa: E501
        :type email: str
        :param name: The name of this UserShort.  # noqa: E501
        :type name: str
        """
        self.openapi_types = {
            'group': UserGroup,
            'email': str,
            'name': str
        }

        self.attribute_map = {
            'group': 'group',
            'email': 'email',
            'name': 'name'
        }

        self._group = group
        self._email = email
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'UserShort':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserShort of this UserShort.  # noqa: E501
        :rtype: UserShort
        """
        return util.deserialize_model(dikt, cls)

    @property
    def group(self) -> UserGroup:
        """Gets the group of this UserShort.


        :return: The group of this UserShort.
        :rtype: UserGroup
        """
        return self._group

    @group.setter
    def group(self, group: UserGroup):
        """Sets the group of this UserShort.


        :param group: The group of this UserShort.
        :type group: UserGroup
        """

        self._group = group

    @property
    def email(self) -> str:
        """Gets the email of this UserShort.


        :return: The email of this UserShort.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this UserShort.


        :param email: The email of this UserShort.
        :type email: str
        """

        self._email = email

    @property
    def name(self) -> str:
        """Gets the name of this UserShort.


        :return: The name of this UserShort.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this UserShort.


        :param name: The name of this UserShort.
        :type name: str
        """

        self._name = name
