version: 1
disable_existing_loggers: False
formatters:
    console:
        format: '[%(asctime)s] <%(filename)s:%(lineno)d> - %(message)s'
        datefmt: '%m.%d %H:%M:%S'
    debug:
        '()': journaling.CustomFormatter
        format: '| [%(asctime)s] | #%(uwsgi)s | %(elapsed)s | <%(filename)s:%(lineno)d> | %(levelname)s | %(message)s'
        datefmt: '%Y.%m.%d %H:%M:%S'
    info:
        '()': journaling.CustomFormatter
        format: '[%(asctime)s] {host=%(host)s} - %(message)s'
        datefmt: '%Y.%m.%d %H:%M:%S'
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: console
        stream: ext://sys.stdout

    debug_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        when: midnight
        level: DEBUG
        formatter: debug
        filename: /var/log/adp/debug.log
        backupCount: 20
        encoding: utf8

    info_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        when: midnight
        level: INFO
        formatter: info
        filename: /var/log/adp/info.log
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        when: midnight
        level: ERROR
        formatter: debug
        filename: /var/log/adp/errors.log
        backupCount: 20
        encoding: utf8

loggers:
    requests:
        level: INFO
        handlers: [info_file_handler]
        propagate: no
    botocore:
        level: ERROR
        handlers: [error_file_handler]
        propagate: no
    s3transfer:
        level: ERROR
        handlers: [error_file_handler]
        propagate: no
    boto3:
        level: ERROR
        handlers: [error_file_handler]
        propagate: no
    urllib3:
        level: ERROR
        handlers: [error_file_handler]
        propagate: no

root:
    level: DEBUG
    handlers: [console, info_file_handler, error_file_handler, debug_file_handler]
